# Generated by Django 2.2 on 2019-04-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_infouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='href',
            field=models.TextField(default='https://docs.djangoproject.com'),
        ),
        migrations.AddField(
            model_name='infouser',
            name='text',
            field=models.TextField(default='Hello'),
        ),
    ]
