# Generated by Django 2.2 on 2019-04-25 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190417_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Инфо', 'verbose_name_plural': 'Инфо Автора'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='article',
            name='href',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='href',
            field=models.TextField(default='https://portfolio-mmrqljtoef.now.sh/', verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='text',
            field=models.TextField(default='Фронтенд разработчик.Так же знаком и с серверной стороной разработки.', verbose_name='Инфо'),
        ),
    ]
